### PR TITLE
Making Pairing Friendly Curves draft reference informative

### PR DESCRIPTION
**Pull request by BasileiosKal**
Redefine the relative functionality from [Pairing-Friendly Curves](https://datatracker.ietf.org/doc/draft-irtf-cfrg-pairing-friendly-curves/) in this draft.

### CODE REVIEW

**Review by OR13 — APPROVED** [review]
even an informative reference to an expired ID will probably cause problems.

**Comment by BasileiosKal** [comment]
> even an informative reference to an expired ID will probably cause problems.

That's true, but it is not "forbidden" (see the [bls sigs](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-05) reference to the [h2c rfc](https://www.rfc-editor.org/rfc/rfc9380.html#I-D.irtf-cfrg-bls-signature)). Even a normative reference is not an issue for the crypto panel review phase (it will certainly be a problem in later stages though).

**Review by Wind4Greg — APPROVED** [review]

**Review by andrewwhitehead — APPROVED** [review]

**Comment by BasileiosKal** [comment]
Discussed on the WG call at the 18th of Dec. Will resolve conflicts and merge after that.

**Comment by BasileiosKal** [comment]
Conflicts resolved. Multiple approvals. Merging. Thank you all!

**Pull request merged**
