### PR TITLE
Add basic test vectors for signature cases

### PR DESCRIPTION
**Pull request by tplooker**
Adds a section for test vectors associated to signature generation and verification, includes an automated script that will allow us to update the fixtures via the input JSON files over time.

### CODE REVIEW

**Comment by quartzjer** [comment]
Uhm, I like this so much I wonder what license the TS bits are under such that I might reuse them? ;)

"Imitation is the sincerest form of flattery"

**Comment by andrewwhitehead** [comment]
Looks good to me!

**Comment by tplooker** [comment]
> Uhm, I like this so much I wonder what license the TS bits are under such that I might reuse them? ;)
> 
> "Imitation is the sincerest form of flattery"

Feel free! Glad it is helpful!

**Comment by tplooker** [comment]
@quartzjer I have updated the tooling script to be licensed under apache 2.0 :)

**Comment by tplooker** [comment]
@andrewwhitehead @mikelodder7 would you be able to test these fixtures out against your implementations for correctness?

**Comment by tplooker** [comment]
A couple of notes about the current set of test fixtures:
- Using the issuer public key derived generators (because we have not merged in the algorithm described in #38 yet
- Deterministic signatures based on #43

**Comment by tplooker** [comment]
I've added a note to the test vectors section that documents the experimental current state of these test vectors

**Review by quartzjer — APPROVED** [review]

**Review by BasileiosKal — APPROVED** [review]

**Comment by tplooker** [comment]
Multiple approvals, test vectors are still marked as experimental, merging

**Pull request merged**
