### PR TITLE
chore: add plain english titles

### LINKED ISSUE #244: Plain English section titles
This is a bit subjective, but I think we should adopt plain English titles for (sub)sections in the draft rather than using function names.

At the moment section 3 looks like this:

    3.1.  Parameters
    3.2.  Considerations
      3.2.1.  Subgroup Selection
      3.2.2.  Messages and generators
      3.2.3.  Serializing to octet strings
    3.3.  Key Generation Operations
      3.3.1.  KeyGen
      3.3.2.  SkToPk
    3.4.  Core Operations
      3.4.1.  Sign
      3.4.2.  Verify
      3.4.3.  ProofGen
      3.4.4.  ProofVerify

An updated version might look like this:

    3.1.  Parameters
    3.2.  Considerations
      3.2.1.  Subgroup Selection
      3.2.2.  Messages and generators
      3.2.3.  Serializing to octet strings
    3.3.  Key Generation Operations
      3.3.1.  Secret Key Generation
      3.3.2.  Public Key Calculation
    3.4.  Core Operations
      3.4.1.  Signing
      3.4.2.  Signature Verification
      3.4.3.  Proof Generation
      3.4.4.  Proof Verification

For comparison the [VOPRF draft](https://cfrg.github.io/draft-irtf-cfrg-voprf/draft-irtf-cfrg-voprf.html).

### PR DESCRIPTION
**Pull request by tplooker**
Adds plain english titles to key sections, fixes #244

### CODE REVIEW

**Comment by BasileiosKal** [comment]
Discussed on the WG call in the 17th of April. Mentioned that having the short term of the operation by the title (i.e., `Proof Generation (ProofGen)`) may not be consistent, since `Sign` for example, is the title and the function name.

A couple more comments:
1. We can get around the above by changing `Sign` to `Signature Generation (Sign)` and `Verify` to `Signature Verification (Verify)`. This will keep everything consistent!
2. Should we change `MapMessageToScalar` to `Map Message to Scalar` and `MapMessageToScalarAsHash` to `Map Message to Scalar as Hash` also?? Same thing for the serialization functions.

So the TOC I propose is
```
3.1.  Parameters
3.2.  Considerations
  3.2.1.  Subgroup Selection
  3.2.2.  Messages and generators
  3.2.3.  Serializing to octet strings
3.3.  Key Generation Operations
  3.3.1.  Secret Key Generation (KeyGen)
  3.3.2.  Public Key Calculation (SkToPk)
3.4.  Core Operations
  3.4.1.  Signature Generation (Sign)
  3.4.2.  Signature Verification (Verify)
  3.4.3.  Proof Generation (ProofGen)
  3.4.4.  Proof Verification (ProofVerify)
4. Utility Operations
  4.1. Random scalars computation
  4.2. Generator point computation
  4.3. Message to Scalar
    4.3.1. Message to Scalar as Hash
  4.4. Hash to Scalar
  4.5. Domain Calculation
  4.6. Challenge Calculation
  4.7. Serialization
    4.7.1. Serialize
    4.7.2. Signature to Octets
    4.7.3. Octets to Signature
    4.7.4. Proof to Octets
    4.7.5. Octets to Proof
    4.7.6. Octets to Public Key
```

**Comment by BasileiosKal** [comment]
Updated PR with the bellow TOC changes (outside of using the clear text English version)

```
KeyGen -> Secret Key
SkToPk -> Public Key

Sign -> Signature Generation (Sign)
Verify -> Signature Verification (Verify)
ProofGen -> Proof Generation (ProofGen)
ProofVerify -> Proof Verification (ProofVerify)

Random scalars computation -> Random Scalars
Generator point computation -> Generators Calculation
MapMessageToScalar -> Message to Scalar
MapMessageToScalarAsHash -> Message to Scalar as Hash
```

**Comment by OR13** [comment]
Yes please to better names

**Review by brentzundel — APPROVED** [review]

**Comment by Wind4Greg** [comment]
Definitely an improvement. +1

**Comment by BasileiosKal** [comment]
Thank you @tmarkovski!

> There is inconsistency though in the 3.4 naming. It feels like the short names from the long form want to be "SignGen", "SignVerify", because "ProofGen" and "ProofVerify", although "SignGen" and "SignVerify" sound very odd.
 
That's a good point, but I would note that the short names are the names of the operations, not the short version of the titles. And yes, "SignGen" sounds very weird 😝.

> Does title case matter in the section titles? "Subgroup Selection" vs "Messages and generators"?

Yes it does. It should be consisted (i.e., everything should be upper case). Thank you for catching this! Fixed.

**Review by christianpaquin — APPROVED** [review]
LGTM

**Comment by tplooker** [comment]
Multiple approvals, editorial improvement, merging.

**Pull request merged**
